questions = [
    "Who are the key witnesses?",
    "Who are the main suspects?",
    "Who are the suspects?",
    "Who are the witnesses?",
    "Who are the victim's friends?",
    "Who are you?",
    "Who called it in?",
    "Who called the police?",
    "Who called to report?",
    "Who called you?",
    "Who can provide an alibi?",
    "Who can verify your alibi?",
    "Who closed the door?",
    "Who cried for help?",
    "Who discovered the body?",
    "Who discovered the body first?",
    "Who disliked the victim?",
    "Who do you believe?",
    "Who do you believe in?",
    "Who do you despise?",
    "Who do you dislike?",
    "Who do you hate?",
    "Who do you idolize?",
    "Who do you like?",
    "Who do you look up to?",
    "Who do you love?",
    "Who do you respect?",
    "Who do you think did it?",
    "Who do you think is stupid?",
    "Who do you trust?",
    "Who do you trust the most?",
    "Who does this bag belong to?",
    "Who does this belong to?",
    "Who does this book belong to?",
    "Who does this item belong to?",
    "Who does this note belong to?",
    "Who did you first speak to?",
    "Who did you first talk to?",
    "Who did you speak to?",
    "Who did you speak to last?",
    "Who did you speak to recently?",
    "Who did you speak to today?",
    "Who did you talk to?",
    "Who did you talk to last?",
    "Who did you talk to recently?",
    "Who did you talk to today?",
    "Who did you talk to yesterday?",
    "Who first discovered the body?",
    "Who first found the body?",
    "Who found the body?",
    "Who found the body first?",
    "Who found the murder weapon?",
    "Who found the evidence?",
    "Who found the evidence first?",
    "Who found the weapon?",
    "Who found this?",
    "Who found this clue?",
    "Who found this item?",
    "Who found this evidence?",
    "Who got an idea?",
    "Who had access to the room?",
    "Who hated the victim?",
    "Who has a motive?",
    "Who has a motive here?",
    "Who has a motive to kill?",
    "Who has a potential motive?",
    "Who has access to the body?",
    "Who has access to the device?",
    "Who has access to the laptop?",
    "Who has access to the room?",
    "Who has access to the weapon?",
    "Who has not been told yet?",
    "Who has not seen the victim?",
    "Who had an alibi?",
    "Who had a motive?",
    "Who had a motive to kill?",
    "Who had a potential motive?",
    "Who had access to the body?",
    "Who had access to the device?",
    "Who had access to the laptop?",
    "Who had access to the room?",
    "Who had access to the weapon?",
    "Who had an alibi?",
    "Who had every right to kill?",
    "Who had the longest hair?",
    "Who had the most money?",
    "Who had the most weight?",
    "Who had the most to gain?",
    "Who had the shortest hair?",
    "Who identified the body?",
    "Who identified the killer?",
    "Who identified the victim?",
    "Who identified the witness?",
    "Who is a genius?",
    "Who is a ghost?",
    "Who is a liar?",
    "Who is a monster?",
    "Who is a vampire?",
    "Who is a villain?",
    "Who is an alien?",
    "Who is an idiot?",
    "Who is alive?",
    "Who is being crazy?",
    "Who is being crazy now?",
    "Who is being stupid?",
    "Who is being stupid now?",
    "Who is crazy?",
    "Who is dead?",
    "Who is dumb?",
    "Who is famous?",
    "Who is going home?",
    "Who is going to kill?",
    "Who is living here?",
    "Who is living here now?",
    "Who is lying?",
    "Who is lying now?",
    "Who is not lying?",
    "Who is not dead?",
    "Who is still alive?",
    "Who is stupid?",
    "Who is telling the truth?",
    "Who is the impostor?",
    "Who is the key witness?",
    "Who is the killer?",
    "Who is the main suspect?",
    "Who is the most suspicious?",
    "Who is the murderer?",
    "Who is the prime minister?",
    "Who is the suspect?",
    "Who is the victim?",
    "Who is the victim's family?",
    "Who is the victim's friend?",
    "Who is the witness?",
    "Who is this?",
    "Who is this call for?",
    "Who is this fingerprint from?",
    "Who is this letter for?",
    "Who is this message for?",
    "Who is this person?",
    "Who is this song for?",
    "Who is this text for?",
    "Who is this threat for?",
    "Who is this warning for?",
    "Who killed the victim?",
    "Who knew about the murder?",
    "Who knew the victim?",
    "Who last saw the killer?",
    "Who last saw the suspect?",
    "Who last saw the victim?",
    "Who last saw the victim alive?",
    "Who last saw the witness?",
    "Who last talked to the victim?",
    "Who lied?",
    "Who lied about their alibi?",
    "Who liked the victim?",
    "Who locked the closet?",
    "Who locked the door?",
    "Who locked the room?",
    "Who loved the victim?",
    "Who lives here?",
    "Who lives near the victim?",
    "Who lives with the victim?",
    "Who lives near you?",
    "Who lives near your house?",
    "Who lives in your house?",
    "Who lives with you?",
    "Who murdered the victim?",
    "Who opened the box?",
    "Who opened the closet?",
    "Who opened the door?",
    "Who reported the crime?",
    "Who reported the murder?",
    "Who set off the alarm?",
    "Who set off the fire alarm?",
    "Who set off the trap?",
    "Who screamed?",
    "Who screamed aloud?",
    "Who screamed loudly?",
    "Who screamed the loudest?",
    "Who spoke to you?",
    "Who spoke to you last?",
    "Who spoke to you recently?",
    "Who started the fire?",
    "Who tampered with the body?",
    "Who tampered with the camera?",
    "Who tampered with the laptop?",
    "Who tampered with the phone?",
    "Who tampered with the photo?",
    "Who tampered with the photos?",
    "Who tampered with the scene?",
    "Who touched the body?",
    "Who touched the button?",
    "Who touched this?",
    "Who touched this item?",
    "Who was acting nervous?",
    "Who was acting nervously?",
    "Who was acting stupid?",
    "Who was acting stupidly?",
    "Who was acting suspicious?",
    "Who was acting suspiciously?",
    "Who was close to the victim?",
    "Who was crying?",
    "Who was crying a moment ago?",
    "Who was crying back then?",
    "Who was crying just now?",
    "Who was dying?",
    "Who was lying?",
    "Who was lying back then?",
    "Who was lying recently?",
    "Who was present at the murder?",
    "Who was present at the time?",
    "Who was screaming?",
    "Who was suspicious?",
    "Who was yelling?",
    "Who were the witnesses?",
    "Who were you speaking to?",
    "Who witnessed the crime?",
    "Who witnessed the event?",
    "Who witnessed the murder?",
    "Who wrote this?",
    "Who wrote this book?",
    "Who wrote this letter?",
    "Who wrote this note?",
    "Who wrote these words?",
    "Who will die?",
    "Who will die first?",
    "Who will die last?",
    "Who will kill?",
    "Who will kill first?",
    "Who will never die?",
    "Who would never cry?",
    "Who would never die?",
    "Who would never hate?",
    "Who would never kill?",
    "Who would you never hate?",
    "Who would you never like?",
    "Who would you never love?",
    "Who would you never kill?",

    "What are the clues?",
    "What are the evidence?",
    "What are the victim's hobbies?",
    "What are you afraid of?",
    "What are you doing here?",
    "What are you doing now?",
    "What are you going to do?",
    "What are you going to do now?",
    "What are you thinking about?",
    "What are you interested in?",
    "What are your hobbies?",
    "What are your interests?",
    "What are your options?",
    "What are your thoughts?",
    "What caused the murder?",
    "What clues are available?",
    "What clues did you find?",
    "What clues lead you here?",
    "What did the clue reveal?",
    "What did the clues reveal?",
    "What did the evidence reveal?",
    "What did the witness hear?",
    "What did the witness recall?",
    "What did the witness record?",
    "What did the witness say?",
    "What did the witness see?",
    "What did the witness see here?",
    "What did the victim hear?",
    "What did the victim record?",
    "What did the victim say?",
    "What did the victim see?",
    "What did the victim see here?",
    "What did you hear?",
    "What did you hear first?",
    "What did you notice?",
    "What did you notice first?",
    "What did you see?",
    "What did you see first?",
    "What do people call you?",
    "What do people think of you?",
    "What do the fingerprints show?",
    "What do the footprints reveal?",
    "What do the footprints show?",
    "What do you believe in?",
    "What do you dislike?",
    "What do you do here?",
    "What do you do in here?",
    "What do you do nowadays?",
    "What do you hate?",
    "What do you hate doing?",
    "What do you like?",
    "What do you like to do?",
    "What do you look forward to?",
    "What do you love to do?",
    "What do you think is missing?",
    "What do you think is weird?",
    "What do you want?",
    "What do you want now?",
    "What do you want to do?",
    "What do you want to do now?",
    "What do you want to do today?",
    "What does this mean?",
    "What does this prove?",
    "What does this reveal?",
    "What does this show?",
    "What does this translate to?",
    "What does your watch read?",
    "What does your watch say?",
    "What evidence is available?",
    "What evidence is there?",
    "What evidence stands out?",
    "What evidence stands out here?",
    "What happened?",
    "What happened here?",
    "What happened over here?",
    "What happened over there?",
    "What happened today?",
    "What happened yesterday?",
    "What is in the barrel?",
    "What is in the box?",
    "What is in the chest?",
    "What is in the locket?",
    "What is in the safe?",
    "What is inside the barrel?",
    "What is inside the box?",
    "What is inside the chest?",
    "What is inside the locket?",
    "What is inside the safe?",
    "What is in the room?",
    "What is this person hiding?",
    "What is this person's problem?",
    "What is this person's secret?",
    "What is this someone?",
    "What is today's date?",
    "What is the best thing to do?",
    "What is the cause of death?",
    "What is the killer's name?",
    "What is the killer's motive?",
    "What is the missing link?",
    "What is the motive?",
    "What is the murder weapon?",
    "What is the suspect's motive?",
    "What is the time of death?",
    "What is the time now?",
    "What is the truth?",
    "What is the victim's name?",
    "What is the witness's name?",
    "What is this place?",
    "What is this thing?",
    "What is your alibi?",
    "What is your best memory?",
    "What is your date of birth?",
    "What is your favorite animal?",
    "What is your favorite anime?",
    "What is your favorite book?",
    "What is your favorite candy?",
    "What is your favorite color?",
    "What is your favorite dessert?",
    "What is your favorite dish?",
    "What is your favorite drink?",
    "What is your favorite food?",
    "What is your favorite game?",
    "What is your favorite hobby?",
    "What is your favorite holiday?",
    "What is your favorite joke?",
    "What is your favorite manga?",
    "What is your favorite memory?",
    "What is your favorite moment?",
    "What is your favorite movie?",
    "What is your favorite quote?",
    "What is your favorite pastime?",
    "What is your favorite person?",
    "What is your favorite place?",
    "What is your favorite planet?",
    "What is your favorite season?",
    "What is your favorite show?",
    "What is your favorite singer?",
    "What is your favorite story?",
    "What is your favorite snack?",
    "What is your favorite sports?",
    "What is your favorite song?",
    "What is your favorite word?",
    "What is your first name?",
    "What is your full name?",
    "What is your last name?",
    "What is your name?",
    "What is your nickname?",
    "What is your story?",
    "What is your talent?",
    "What is your type?",
    "What killed the victim?",
    "What motivated the killer?",
    "What should you be doing now?",
    "What should you do?",
    "What should you do now?",
    "What time did it happen?",
    "What time did it occur?",
    "What time did the victim die?",
    "What time did this happen?",
    "What time did this occur?",
    "What time is it?",
    "What time is it now?",
    "What time was the murder?",
    "What was found near the body?",
    "What was found near the table?",
    "What was found in the barrel?",
    "What was found in the box?",
    "What was found in the chest?",
    "What was found in the locket?",
    "What was found in the safe?",
    "What was found inside the box?",
    "What was found on the body?",
    "What was found on the table?",
    "What was found under the body?",
    "What was in the barrel?",
    "What was in the box?",
    "What was in the chest?",
    "What was in the locket?",
    "What was in the safe?",
    "What was near the body?",
    "What was near the table?",
    "What was on the body?",
    "What was on the table?",
    "What was the cause of death?",
    "What was the killer's motive?",
    "What was the suspect's motive?",
    "What was the motive?",
    "What was the time of death?",
    "What was the victim's hobbies?",
    "What was the victim's name?",
    "What was the victim doing?",
    "What was under the body?",
    "What was underneath the body?",
    "What were you doing?",
    "What were you doing just now?",
    "What were you doing yesterday?",
    "What were you reading?",
    "What were you reading now?",
    "What will never die?",
    "What would never die?",

    "When are you going home?",
    "When are you leaving?",
    "When did the crime happen?",
    "When did the crime occur?",
    "When did the killer arrive?",
    "When did the killer go?",
    "When did the killer leave?",
    "When did the murder happen?",
    "When did the murder occur?",
    "When did the suspect arrive?",
    "When did the suspect go?",
    "When did the suspect leave?",
    "When did the victim arrive?",
    "When did the victim die?",
    "When did the victim go?",
    "When did the victim leave?",
    "When did the witness arrive?",
    "When did the witness go?",
    "When did the witness leave?",
    "When did you arrive?",
    "When did you arrive here?",
    "When did you eat?",
    "When did you get here?",
    "When did you go?",
    "When did you go home?",
    "When did you go home last night?",
    "When did you go last night?",
    "When did you last see a movie?",
    "When did you last sleep?",
    "When did you sleep?",
    "When did you sleep last night?",
    "When did you wake up?",
    "When is the festival?",
    "When is this place closed?",
    "When is this place open?",
    "When is your birthday?",
    "When was the body discovered?",
    "When was the body first seen?",
    "When was the body found?",
    "When was the body last seen?",
    "When was the body reported?",
    "When was the body seen?",
    "When was the crime reported?",
    "When was the killer seen?",
    "When was the killer last seen?",
    "When was the murder reported?",
    "When was the victim last seen?",
    "When was the victim found?",
    "When was the victim seen?",
    "When will the train arrive?",
    "When will this begin?",
    "When will this close?",
    "When will this open?",
    "When will this stop?",
    "When will this start?",
    "When will this door open?",
    "When will this place open?",
    "When were you born?",
    "When will you go?",
    "When will you graduate?",
    "When will you leave?",
    "When will you wake up?",

    "Where are the bodies?",
    "Where are the clues?",
    "Where are the killers?",
    "Where are the suspects?",
    "Where are the victims?",
    "Where are the witnesses?",
    "Where are you going?",
    "Where are you going now?",
    "Where are you going to?",
    "Where are you hurt?",
    "Where are you hurting?",
    "Where are you living?",
    "Where are you living now?",
    "Where can one find batteries?",
    "Where can one find diamonds?",
    "Where can one find the body?",
    "Where can one find the victim?",
    "Where can you find batteries?",
    "Where can you find diamonds?",
    "Where can you find the body?",
    "Where can you find the victim?",
    "Where did the crime happen?",
    "Where did the crime occur?",
    "Where did the killer go?",
    "Where did the murder happen?",
    "Where did the murder occur?",
    "Where did the suspect go?",
    "Where did the victim die?",
    "Where did the victim go?",
    "Where did the witness go?",
    "Where did you arrive?",
    "Where did you arrive here?",
    "Where did you find the clue?",
    "Where did you find the key?",
    "Where did you find the weapon?",
    "Where did you eat?",
    "Where did you go?",
    "Where did you go last night?",
    "Where did you last sleep?",
    "Where did you sleep?",
    "Where did you wake up?",
    "Where do babies come from?",
    "Where do you live?",
    "Where do you live now?",
    "Where do you currently live?",
    "Where does it hurt?",
    "Where does it hurt now?",
    "Where is the attic?",
    "Where is the basement?",
    "Where is the bathroom?",
    "Where is the body?",
    "Where is the clue?",
    "Where is the crime scene?",
    "Where is the evidence?",
    "Where is the festival?",
    "Where is the hotel?",
    "Where is the killer?",
    "Where is the killer now?",
    "Where is the meaning of life?",
    "Where is the murder weapon?",
    "Where is the nearest bathroom?",
    "Where is the roof?",
    "Where is the rooftop?",
    "Where is the suspect?",
    "Where is the suspect now?",
    "Where is the train?",
    "Where is the victim?",
    "Where is the victim now?",
    "Where is the witness?",
    "Where is the witness now?",
    "Where is this fingerprint from?",
    "Where is this person hiding?",
    "Where are these fingerprints from?",
    "Where is your cellphone?",
    "Where is your smartphone?",
    "Where is your phone?",
    "Where was the body discovered?",
    "Where was the body first seen?",
    "Where was the body found?",
    "Where was the body last seen?",
    "Where was the body reported?",
    "Where was the body seen?",
    "Where was the crime reported?",
    "Where was the killer?",
    "Where was the killer seen?",
    "Where was the murder reported?",
    "Where was the weapon found?",
    "Where was the victim?",
    "Where was the victim found?",
    "Where was the victim seen?",
    "Where were you?",
    "Where were you a moment ago?",
    "Where were you born?",
    "Where were you just now?",
    "Where will you go?",
    "Where will you leave?",

    "Why are you acting creepy?",
    "Why are you acting strange?",
    "Why are you acting strangely?",
    "Why are you acting suspicious?",
    "Why are you angry?",
    "Why are you anxious?",
    "Why are you alive?",
    "Why are you annoyed?",
    "Why are you being stubborn?",
    "Why are you bored?",
    "Why are you crying?",
    "Why are you different?",
    "Why are you doing this?",
    "Why are you early?",
    "Why are you exhausted?",
    "Why are you feeling angry?",
    "Why are you feeling anxious?",
    "Why are you feeling exhausted?",
    "Why are you feeling furious?",
    "Why are you feeling happy?",
    "Why are you feeling hesistant?",
    "Why are you feeling irate?",
    "Why are you feeling irritated?",
    "Why are you feeling livid?",
    "Why are you feeling mad?",
    "Why are you feeling sad?",
    "Why are you feeling scared?",
    "Why are you feeling sleepy?",
    "Why are you feeling reluctant?",
    "Why are you feeling tired?",
    "Why are you feeling upset?",
    "Why are you furious?",
    "Why are you happy?",
    "Why are you helping?",
    "Why are you here?",
    "Why are you hesistant?",
    "Why are you hesistant to help?",
    "Why are you hesistant to talk?",
    "Why are you irate?",
    "Why are you irritated?",
    "Why are you late?",
    "Why are you livid?",
    "Why are you lying?",
    "Why are you mad?",
    "Why are you quiet?",
    "Why are you reluctant?",
    "Why are you reluctant to help?",
    "Why are you reluctant to talk?",
    "Why are you running?",
    "Why are you running away?",
    "Why are you running off?",
    "Why are you sad?",
    "Why are you scared?",
    "Why are you screaming?",
    "Why are you seething?",
    "Why are you sleeping?",
    "Why are you sleepy?",
    "Why are you so happy?",
    "Why are you so quiet?",
    "Why are you still alive?",
    "Why are you still here?",
    "Why are you the killer?",
    "Why are you tired?",
    "Why are you upset?",
    "Why are you yelling?",
    "Why can't you just listen?",
    "Why can't you listen?",
    "Why can't you talk?",
    "Why do you want to be here?",
    "Why did the killer flee?",
    "Why did the suspect flee?",
    "Why did the witness flee?",
    "Why did the victim die?",
    "Why did the victim fight back?",
    "Why did you act scared?",
    "Why did you change?",
    "Why did you change your alibi?",
    "Why did you change your story?",
    "Why did you failed to act?",
    "Why did you feel cold?",
    "Why did you feel hot?",
    "Why did you feel nervous?",
    "Why did you feel scared?",
    "Why did you hesistate to kill?",
    "Why did you kill the victim?",
    "Why did you leave this behind?",
    "Why did you make that letter?",
    "Why did you make that remark?",
    "Why did you not say anything?",
    "Why did you run away?",
    "Why did you say that?",
    "Why did you send that letter?",
    "Why did you send that message?",
    "Why did you send that text?",
    "Why did you send that threat?",
    "Why did you send that warning?",
    "Why did you tell that?",
    "Why did you write this?",
    "Why didn't the victim flee?",
    "Why didn't you say anything?",
    "Why is the body missing?",
    "Why is the this missing?",
    "Why is the weapon missing?",
    "Why is the victim dead?",
    "Why is the victim here?",
    "Why was the body hidden?",
    "Why was the body missing?",
    "Why was the victim killed?",
    "Why was the victim targeted?",
    "Why was this left behind?",
    "Why would you do this?",
    "Why would you kill the victim?",
];